# -*- coding: utf-8 -*-
"""Classification model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZOI-ZQgqIQ2gAmSYgAytCEuidmgQb58
"""

# Import Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Create Dataset
data = {
    'Hours_Studied':[1,2,3,4,5,6,7,8,2,5,6,7],
    'Attendance':[60,65,70,75,80,85,90,95,68,82,88,91],
    'Pass':[0,0,0,1,1,1,1,1,0,1,1,1]
}

df = pd.DataFrame(data)

# Features and Target
X = df[['Hours_Studied','Attendance']]
y = df['Pass']

# Split Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# Train Model
model = LogisticRegression()
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Predicted Values:", y_pred)
print("Actual Values:", list(y_test))
print("Accuracy:", accuracy)