# -*- coding: utf-8 -*-
"""Linear regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18qPnj04P1wPr4zK-ZDpzr6oBt2UWF22e
"""

# Import Libraries
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Generate Synthetic Dataset
np.random.seed(42)

X = np.random.rand(100) * 10
Y = 3 * X + 5 + np.random.randn(100) * 2

# Step 2: Calculate Slope (m) and Intercept (b)

mean_x = np.mean(X)
mean_y = np.mean(Y)

m = np.sum((X - mean_x) * (Y - mean_y)) / np.sum((X - mean_x) ** 2)
b = mean_y - m * mean_x

print("Slope (m):", m)
print("Intercept (b):", b)

# Step 3: Predict Values

Y_pred = m * X + b

# Step 4: Evaluation Metrics

# MAE
mae = np.mean(np.abs(Y - Y_pred))

# MSE
mse = np.mean((Y - Y_pred) ** 2)

# R² Score
ss_total = np.sum((Y - mean_y) ** 2)
ss_residual = np.sum((Y - Y_pred) ** 2)

r2 = 1 - (ss_residual / ss_total)

print("\nEvaluation Metrics")
print("MAE :", mae)
print("MSE :", mse)
print("R² Score :", r2)

# Step 5: Plot Graph

plt.scatter(X, Y, color='blue', label='Data Points')
plt.plot(X, Y_pred, color='red', label='Regression Line')

plt.title("Linear Regression from Scratch")
plt.xlabel("X")
plt.ylabel("Y")
plt.legend()

plt.show()